name: jada_fit
description: "The perfect fit-pal."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.11.4

dependencies:
  flutter:
    sdk: flutter
  # HTTP para las llamadas a tu API
  http: ^1.2.2
  # Secure Storage para guardar el JWT sin riesgos
  flutter_secure_storage: ^9.2.2
  # Provider para gestionar el estado del login
  provider: ^6.1.1
  # Iconos de iOS
  cupertino_icons: ^1.0.8
  font_awesome_flutter: ^10.7.0
  # Escaneo de QR y códigos de barras
  mobile_scanner: ^7.1.3
  # Gráficos
  fl_chart: ^0.69.0
  # Notificaciones
  flutter_local_notifications: ^18.0.0
  # Renderizar Markdown en respuestas de IA
  flutter_markdown: ^0.7.6
  shimmer: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true